// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayAway.WebAPI.DB;

namespace PayAway.WebAPI.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    [Migration("20201113183734_Milestone2SeedData")]
    partial class Milestone2SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("PayAway.WebAPI.Entities.v1.CatalogItemDBE", b =>
                {
                    b.Property<Guid>("MerchantID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemUnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("MerchantID", "ItemGuid");

                    b.HasIndex("MerchantID", "ItemName")
                        .IsUnique();

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("PayAway.WebAPI.Entities.v1.CustomerDBE", b =>
                {
                    b.Property<Guid>("MerchantID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhoneNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MerchantID", "CustomerID");

                    b.HasIndex("MerchantID", "CustomerPhoneNo")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PayAway.WebAPI.Entities.v1.MerchantDBE", b =>
                {
                    b.Property<Guid>("MerchantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSupportsTips")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MerchantID");

                    b.HasIndex("MerchantName")
                        .IsUnique();

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("PayAway.WebAPI.Entities.v1.OrderDBE", b =>
                {
                    b.Property<Guid>("OrderGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDateTimeUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderGuid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PayAway.WebAPI.Entities.v1.OrderEventDBE", b =>
                {
                    b.Property<Guid>("OrderGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventGuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDateTimeUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderGuid", "EventGuid");

                    b.ToTable("OrderEvents");
                });

            modelBuilder.Entity("PayAway.WebAPI.Entities.v1.OrderItemDBE", b =>
                {
                    b.Property<Guid>("OrderGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemUnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderGuid", "ItemGuid");

                    b.ToTable("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
